# Generated by Django 3.0.6 on 2020-05-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='survey_id',
            new_name='quizz_id',
        ),
    ]
