# Generated by Django 3.0.6 on 2020-05-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0002_auto_20200520_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='timer_secs',
            field=models.IntegerField(default=0),
        ),
    ]
