# Generated by Django 3.0.6 on 2020-05-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0003_quizzes_timer_secs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='timer_secs',
            field=models.IntegerField(default=60),
        ),
    ]
